spring:
 datasource: url=jdbc:h2:file:/db.migration/schema
jpa:
  show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  output:
    ansi:
      enabled: always
